"""feat: add product interactions table

Revision ID: 14ae4a145cd2
Revises: cb2fb1307d31
Create Date: 2026-09-27 22:21:58.050089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ae4a145cd2'
down_revision: Union[str, Sequence[str], None] = 'cb2fb1307d31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_interactions_customer_id'), 'product_interactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_product_interactions_product_id'), 'product_interactions', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_interactions_product_id'), table_name='product_interactions')
    op.drop_index(op.f('ix_product_interactions_customer_id'), table_name='product_interactions')
    op.drop_table('product_interactions')
    # ### end Alembic commands ###
