"""chore: add empty sanity-check migration

Revision ID: cb2fb1307d31
Revises:
Create Date: 2026-08-06 17:59:59.193301

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "cb2fb1307d31"  # pragma: allowlist secret
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
